'use strict';
function syncDocumentControls(){levelName.value=map.meta?.name||'Nova fase';resetCollectibles.checked=!!map.settings.resetCollectiblesOnDeath;resetLogic.checked=!!map.settings.resetLogicOnDeath;resetEnemies.checked=!!map.settings.resetEnemiesOnDeath;mapColsInput.value=gridCols();mapRowsInput.value=gridRows();if(backgroundColor)backgroundColor.value=safeHexColor(map.background?.color,'#d9e6ff');if(backgroundHex)backgroundHex.value=safeHexColor(map.background?.color,'#d9e6ff');}
function syncLevelNameFromInput({finalize=false}={}){let name=cleanText(levelName.value,SECURITY.MAX_LEVEL_NAME,'');if(finalize&&!name)name='Nova fase';if(finalize||levelName.value.length>SECURITY.MAX_LEVEL_NAME)levelName.value=name||'Nova fase';map.meta.name=name||'Nova fase';safeAutosave();return map.meta.name;}
levelName.addEventListener('input',()=>syncLevelNameFromInput());levelName.addEventListener('change',()=>{syncLevelNameFromInput({finalize:true});commit();});resetCollectibles.onchange=()=>{map.settings.resetCollectiblesOnDeath=resetCollectibles.checked;commit();};resetLogic.onchange=()=>{map.settings.resetLogicOnDeath=resetLogic.checked;commit();};resetEnemies.onchange=()=>{map.settings.resetEnemiesOnDeath=resetEnemies.checked;commit();};
$('applyMapSize').onclick=()=>{const newCols=clamp(Number(mapColsInput.value)||30,10,120),newRows=clamp(Number(mapRowsInput.value)||18,8,80),shrinking=newCols<gridCols()||newRows<gridRows();if(shrinking&&!confirm('Diminuir o mapa pode remover ou ajustar objetos fora da nova área. Deseja continuar?')){syncDocumentControls();return;}map.grid.cols=newCols;map.grid.rows=newRows;resizeCanvas();fitMapToGrid();clearSelection();commit();draw();setStatus(`Mapa redimensionado para ${newCols}×${newRows}.`);};

function applyBackgroundColor(value,commitChange=true){const color=safeHexColor(value,map.background?.color||'#d9e6ff');map.background={color};if(backgroundColor)backgroundColor.value=color;if(backgroundHex)backgroundHex.value=color;draw();if(commitChange)commit();}
if(backgroundColor)backgroundColor.addEventListener('input',()=>applyBackgroundColor(backgroundColor.value,false));
if(backgroundColor)backgroundColor.addEventListener('change',()=>applyBackgroundColor(backgroundColor.value,true));
if(backgroundHex)backgroundHex.addEventListener('change',()=>applyBackgroundColor(backgroundHex.value,true));
