/* src/core/config.js */
'use strict';

// Configuração global do editor.
const CELL = 32;
const keys = {};


/* src/core/security.js */
'use strict';
const SECURITY = Object.freeze({
  MAX_IMPORT_BYTES:2500000,MAX_JSON_CHARS:2500000,MAX_LEVEL_NAME:80,MAX_TEMPLATE_NAME:80,MAX_TEMPLATES:100,
  MAX_WALLS:4000,MAX_ENEMIES:500,MAX_PORTALS:1000,MAX_CHECKPOINTS:2000,MAX_KEY_DOORS:1000,MAX_BUTTONS:2000,MAX_COINS:8000,
  MAX_ROUTE_POINTS_PER_ENEMY:512,MAX_TOTAL_ROUTE_POINTS:10000,MAX_TOTAL_OBJECTS:12000,MAX_ID:2147483647
});
function isRecord(v){return !!v&&typeof v==='object'&&!Array.isArray(v);}
function cleanText(v,max=80,f=''){const s=String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);return s||f;}
function finiteNumber(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function finiteInteger(v,f=0){return Math.trunc(finiteNumber(v,f));}
function safeBoolean(v,f=false){return typeof v==='boolean'?v:f;}
function parseJsonWithLimit(text,max=SECURITY.MAX_JSON_CHARS){const s=String(text??'');if(s.length>max)throw new Error(`JSON excede o limite de ${Math.round(max/1000000*10)/10} MB.`);return JSON.parse(s);}
function mapInputStats(data){const s={walls:Array.isArray(data?.walls)?data.walls.length:0,enemies:Array.isArray(data?.enemies)?data.enemies.length:0,portals:Array.isArray(data?.portals)?data.portals.length:0,checkpoints:Array.isArray(data?.checkpoints)?data.checkpoints.length:0,keyDoors:Array.isArray(data?.keyDoors)?data.keyDoors.length:0,buttons:Array.isArray(data?.buttons)?data.buttons.length:0,coins:Array.isArray(data?.coins)?data.coins.length:0,routePoints:0};if(Array.isArray(data?.enemies))for(const e of data.enemies)if(Array.isArray(e?.route))s.routePoints+=e.route.length;s.totalObjects=s.walls+s.enemies+s.portals+s.checkpoints+s.keyDoors+s.buttons+s.coins+2;return s;}
function assertMapInputLimits(data){if(!isRecord(data))throw new Error('O JSON precisa conter um objeto de mapa na raiz.');const ls=[['walls',SECURITY.MAX_WALLS,'paredes'],['enemies',SECURITY.MAX_ENEMIES,'inimigos'],['portals',SECURITY.MAX_PORTALS,'portais'],['checkpoints',SECURITY.MAX_CHECKPOINTS,'checkpoints'],['keyDoors',SECURITY.MAX_KEY_DOORS,'chaves/portas'],['buttons',SECURITY.MAX_BUTTONS,'botões'],['coins',SECURITY.MAX_COINS,'moedas']];for(const [k,m,l] of ls){const v=data[k];if(v!==undefined&&!Array.isArray(v))throw new Error(`Campo “${k}” inválido: era esperado um array.`);if(Array.isArray(v)&&v.length>m)throw new Error(`Mapa recusado: máximo de ${m} ${l}.`);}let rp=0;if(Array.isArray(data.enemies))for(const e of data.enemies){if(!isRecord(e))continue;if(e.route!==undefined&&!Array.isArray(e.route))throw new Error('Rota de inimigo inválida.');if(Array.isArray(e.route)){if(e.route.length>SECURITY.MAX_ROUTE_POINTS_PER_ENEMY)throw new Error(`Mapa recusado: uma rota possui mais de ${SECURITY.MAX_ROUTE_POINTS_PER_ENEMY} pontos.`);rp+=e.route.length;}}if(rp>SECURITY.MAX_TOTAL_ROUTE_POINTS)throw new Error(`Mapa recusado: máximo de ${SECURITY.MAX_TOTAL_ROUTE_POINTS} pontos de rota no total.`);const s=mapInputStats(data);if(s.totalObjects>SECURITY.MAX_TOTAL_OBJECTS)throw new Error(`Mapa recusado: máximo de ${SECURITY.MAX_TOTAL_OBJECTS} objetos.`);return s;}
function parseMapJson(text){const d=parseJsonWithLimit(text);assertMapInputLimits(d);return d;}
function cloneJson(v){return JSON.parse(JSON.stringify(v));}
function collectionLimit(k){return ({walls:SECURITY.MAX_WALLS,enemies:SECURITY.MAX_ENEMIES,portals:SECURITY.MAX_PORTALS,checkpoints:SECURITY.MAX_CHECKPOINTS,keyDoors:SECURITY.MAX_KEY_DOORS,buttons:SECURITY.MAX_BUTTONS,coins:SECURITY.MAX_COINS})[k]||SECURITY.MAX_TOTAL_OBJECTS;}
function canAddToCollection(k,a=1){const l=map?.[k],m=collectionLimit(k);if(!Array.isArray(l))return false;if(l.length+a<=m)return true;setStatus(`Limite de segurança atingido: ${m} item(ns) em ${k}.`);return false;}


/* src/core/dom.js */
'use strict';

// Referências aos elementos da interface.
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d');
const status=$('status'),stats=$('stats'),cursorLabel=$('cursorLabel'),modeLabel=$('modeLabel');
const jsonArea=$('jsonArea'),fileInput=$('fileInput'),levelName=$('levelName');
const snapSelect=$('snapSelect'),enemySpeed=$('enemySpeed');
const props=$('properties'),emptySelection=$('emptySelection'),selectedInfo=$('selectedInfo');
const wallProps=$('wallProps'),enemyProps=$('enemyProps'),staticProps=$('staticProps'),regularProps=$('regularProps'),guidedProps=$('guidedProps');
const wallW=$('wallW'),wallH=$('wallH'),editEnemySpeed=$('editEnemySpeed'),editMoveMode=$('editMoveMode');
const startX=$('startX'),startY=$('startY'),endX=$('endX'),endY=$('endY'),freeAngle=$('freeAngle'),freeAngleInput=$('freeAngleInput');
const routeInfo=$('routeInfo'),guidedSpeed=$('guidedSpeed');
const finishGuideBtn=$('finishGuideBtn'),cancelGuideBtn=$('cancelGuideBtn');
const resetCollectibles=$('resetCollectibles'),resetLogic=$('resetLogic'),resetEnemies=$('resetEnemies');
const autosaveLabel=$('autosaveLabel'), mapColsInput=$('mapCols'), mapRowsInput=$('mapRows');
const canvasWrap = canvas.closest('.canvasWrap');
const zoomOutBtn=$('zoomOutBtn'),zoomInBtn=$('zoomInBtn'),zoomResetBtn=$('zoomResetBtn');
const duplicateBtn=$('duplicateBtn'),copyBtn=$('copyBtn'),pasteBtn=$('pasteBtn'),validateBtn=$('validateBtn');
const duplicateSelectedBtn=$('duplicateSelectedBtn'),copySelectedBtn=$('copySelectedBtn');
const templateSelect=$('templateSelect'),loadTemplateBtn=$('loadTemplateBtn'),saveTemplateBtn=$('saveTemplateBtn'),deleteTemplateBtn=$('deleteTemplateBtn');
const runValidationBtn=$('runValidationBtn'),validationSummary=$('validationSummary'),validationList=$('validationList');


/* src/core/model.js */
'use strict';
function gridCols(){return map.grid?.cols||30;}function gridRows(){return map.grid?.rows||18;}function canvasW(){return gridCols()*CELL;}function canvasH(){return gridRows()*CELL;}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function maxX(){return canvas.width;}function maxY(){return canvas.height;}function resizeCanvas(){canvas.width=canvasW();canvas.height=canvasH();}function insideCell(c,r){return c>=0&&r>=0&&c<gridCols()&&r<gridRows();}function clampPointToCanvas(p){return{x:clamp(finiteNumber(p?.x,0),0,Math.max(0,canvasW())),y:clamp(finiteNumber(p?.y,0),0,Math.max(0,canvasH()))};}
function freshMap(){return{version:7,meta:{name:'Nova fase'},grid:{cols:30,rows:18},settings:{resetCollectiblesOnDeath:false,resetLogicOnDeath:false,resetEnemiesOnDeath:false},spawn:{c:1,r:8},goal:{c:28,r:8},walls:[],enemies:[],portals:[],checkpoints:[],keyDoors:[],buttons:[],coins:[]};}
function nextId(arr){return arr.reduce((m,x)=>Math.max(m,Number(x.id)||0),0)+1;}function normAngle(a){a=finiteNumber(a,0);return((a%360)+360)%360;}function sameCell(a,c,r){return!!a&&a.c===c&&a.r===r;}function cellCenter(c,r){return{x:(c+.5)*CELL,y:(r+.5)*CELL};}function snap(v){const s=Math.max(1,finiteNumber(snapSelect.value,1));return Math.round(v/s)*s;}function snapPoint(p){return clampPointToCanvas({x:snap(p.x),y:snap(p.y)});}function wallContains(w,c,r){return c>=w.c&&r>=w.r&&c<w.c+w.w&&r<w.r+w.h;}function wallAt(c,r){return map.walls.find(w=>wallContains(w,c,r));}function pointInCell(x,y,c,r){return Math.floor(x/CELL)===c&&Math.floor(y/CELL)===r;}function enemyAnchor(e){return e.type==='guided'?e.route[0]:e.type==='static'?{x:e.x,y:e.y}:e.start;}function enemyAtPoint(x,y){return map.enemies.find(e=>{const p=enemyAnchor(e);return p&&Math.hypot(p.x-x,p.y-y)<=16;});}function targetKey(t){return!t?'':`${t.kind}:${t.id}`;}
function makeIdAllocator(){const used=new Set();let cursor=1;return raw=>{const c=finiteInteger(raw,0);if(c>0&&c<=SECURITY.MAX_ID&&!used.has(c)){used.add(c);cursor=Math.max(cursor,c+1);return c;}while(used.has(cursor)&&cursor<SECURITY.MAX_ID)cursor++;const id=clamp(cursor,1,SECURITY.MAX_ID);used.add(id);cursor=id+1;return id;};}
function safeCell(raw,f={c:0,r:0}){return{c:finiteInteger(raw?.c,f.c),r:finiteInteger(raw?.r,f.r)};}
function fitMapToGrid(){const cols=gridCols(),rows=gridRows();map.spawn.c=clamp(map.spawn.c,0,cols-1);map.spawn.r=clamp(map.spawn.r,0,rows-1);map.goal.c=clamp(map.goal.c,0,cols-1);map.goal.r=clamp(map.goal.r,0,rows-1);map.walls=map.walls.filter(w=>w.c<cols&&w.r<rows&&w.c+w.w>0&&w.r+w.h>0).map(w=>{const c=clamp(w.c,0,cols-1),r=clamp(w.r,0,rows-1);return{...w,c,r,w:clamp(w.w,1,cols-c),h:clamp(w.h,1,rows-r)};});const keep=o=>insideCell(o.c,o.r);map.checkpoints=map.checkpoints.filter(keep);map.coins=map.coins.filter(keep);map.portals=map.portals.filter(p=>insideCell(p.a.c,p.a.r)&&insideCell(p.b.c,p.b.r));map.keyDoors=map.keyDoors.filter(k=>insideCell(k.key.c,k.key.r)&&insideCell(k.door.c,k.door.r));map.buttons=map.buttons.filter(b=>insideCell(b.pos.c,b.pos.r));map.enemies=map.enemies.map(e=>{if(e.type==='static')return{...e,...clampPointToCanvas({x:e.x,y:e.y})};if(e.type==='guided'){const route=(e.route||[]).map(clampPointToCanvas);return{...e,route:route.length>=2?route:[{x:64,y:64},{x:160,y:64}]};}return{...e,start:clampPointToCanvas(e.start||{x:64,y:64}),end:clampPointToCanvas(e.end||{x:160,y:64}),angle:normAngle(e.angle)};});const enemyIds=new Set(map.enemies.map(e=>e.id)),wallIds=new Set(map.walls.map(w=>w.id)),doorIds=new Set(map.keyDoors.map(k=>k.id));map.buttons=map.buttons.filter(b=>{if(!b.target)return false;if(b.target.kind==='enemy')return enemyIds.has(b.target.id);if(b.target.kind==='wall')return wallIds.has(b.target.id);if(b.target.kind==='door')return doorIds.has(b.target.id);return false;});}
function normalizeMap(data){assertMapInputLimits(data);const raw=isRecord(data)?data:{},g=isRecord(raw.grid)?raw.grid:{},m=isRecord(raw.meta)?raw.meta:{},st=isRecord(raw.settings)?raw.settings:{};const out=freshMap();out.meta.name=cleanText(m.name,SECURITY.MAX_LEVEL_NAME,'Nova fase');out.grid.cols=clamp(finiteInteger(g.cols,30),10,120);out.grid.rows=clamp(finiteInteger(g.rows,18),8,80);out.settings={resetCollectiblesOnDeath:safeBoolean(st.resetCollectiblesOnDeath,false),resetLogicOnDeath:safeBoolean(st.resetLogicOnDeath,false),resetEnemiesOnDeath:safeBoolean(st.resetEnemiesOnDeath,false)};out.spawn=safeCell(raw.spawn,{c:1,r:8});out.goal=safeCell(raw.goal,{c:28,r:8});
const wallId=makeIdAllocator();out.walls=(Array.isArray(raw.walls)?raw.walls:[]).filter(isRecord).map(w=>({id:wallId(w.id),c:finiteInteger(w.c,0),r:finiteInteger(w.r,0),w:Math.max(1,finiteInteger(w.w,1)),h:Math.max(1,finiteInteger(w.h,1))}));
const enemyId=makeIdAllocator();out.enemies=(Array.isArray(raw.enemies)?raw.enemies:[]).filter(isRecord).map(e=>{const id=enemyId(e.id);if(e.type==='guided'&&Array.isArray(e.route)){const route=e.route.filter(isRecord).slice(0,SECURITY.MAX_ROUTE_POINTS_PER_ENEMY).map(p=>({x:finiteNumber(p.x,0),y:finiteNumber(p.y,0)}));return{id,type:'guided',speed:clamp(finiteNumber(e.speed,90),1,1000),route:route.length>=2?route:[{x:64,y:64},{x:192,y:64}]};}if(e.type==='static'){const x=Number.isFinite(Number(e.x))?Number(e.x):(finiteNumber(e.c,0)+.5)*CELL,y=Number.isFinite(Number(e.y))?Number(e.y):(finiteNumber(e.r,0)+.5)*CELL;return{id,type:'static',x,y};}const sx=Number.isFinite(Number(e.start?.x))?Number(e.start.x):(Number.isFinite(Number(e.x))?Number(e.x):(finiteNumber(e.c,0)+.5)*CELL),sy=Number.isFinite(Number(e.start?.y))?Number(e.start.y):(Number.isFinite(Number(e.y))?Number(e.y):(finiteNumber(e.r,0)+.5)*CELL),angle=Number.isFinite(Number(e.angle))?normAngle(e.angle):(e.type==='vertical'?90:0),sp=clamp(finiteNumber(e.speed,90),1,1000),ex=Number.isFinite(Number(e.end?.x))?Number(e.end.x):sx+Math.cos(angle*Math.PI/180)*CELL*4,ey=Number.isFinite(Number(e.end?.y))?Number(e.end.y):sy+Math.sin(angle*Math.PI/180)*CELL*4;return{id,type:'moving',mode:e.mode==='free'?'free':'patrol',speed:sp,start:{x:sx,y:sy},end:{x:ex,y:ey},angle};});
const portalId=makeIdAllocator();out.portals=(Array.isArray(raw.portals)?raw.portals:[]).filter(isRecord).map(p=>({id:portalId(p.id),a:safeCell(p.a),b:safeCell(p.b)}));const checkpointId=makeIdAllocator();out.checkpoints=(Array.isArray(raw.checkpoints)?raw.checkpoints:[]).filter(isRecord).map(cp=>({id:checkpointId(cp.id),...safeCell(cp)}));const keyDoorId=makeIdAllocator();out.keyDoors=(Array.isArray(raw.keyDoors)?raw.keyDoors:[]).filter(isRecord).map(k=>({id:keyDoorId(k.id),key:safeCell(k.key),door:safeCell(k.door)}));const coinId=makeIdAllocator();out.coins=(Array.isArray(raw.coins)?raw.coins:[]).filter(isRecord).map(c=>({id:coinId(c.id),...safeCell(c)}));const buttonId=makeIdAllocator();out.buttons=(Array.isArray(raw.buttons)?raw.buttons:[]).filter(isRecord).map(b=>{const kind=['wall','enemy','door'].includes(b.target?.kind)?b.target.kind:'',tid=finiteInteger(b.target?.id,0);return{id:buttonId(b.id),pos:safeCell(b.pos),target:kind&&tid>0&&tid<=SECURITY.MAX_ID?{kind,id:tid}:null};});map=out;resizeCanvas();fitMapToGrid();map.version=7;return map;}


/* src/core/state.js */
'use strict';
let mode='edit',tool='wall',dragging=false,deaths=0,won=false,raf=null,last=0;
let map=freshMap(),selected=null;
let pendingPortal=null,pendingKey=null,pendingButton=null,pendingPatrol=null,pendingGuide=null;
let appendRouteTarget=null,routeDrag=null;
let player=null,simEnemies=[],collectedCoins=new Set(),collectedKeys=new Set(),disabledTargets=new Set();
let activeCheckpoint=null,respawnPoint=null,buttonInside=new Set();
let history=[],historyIndex=-1,historyLock=false;
let viewportZoom=1,panState=null,spacePan=false;
let selectedItems=[],clipboardItems=[],selectToggleMode=false,selectionRect=null,selectionStart=null;
let templatesCache=[];


/* src/core/history.js */
'use strict';function snapshot(){return JSON.stringify(map);}function safeAutosave(){try{assertMapInputLimits(map);const d=snapshot();if(d.length>SECURITY.MAX_JSON_CHARS)throw new Error();localStorage.setItem('sanMapEditorV11Draft',d);autosaveLabel.textContent='Rascunho local: salvo automaticamente';}catch{autosaveLabel.textContent='Rascunho local: indisponível ou acima do limite de segurança';}}function updateHistoryButtons(){$('undoBtn').disabled=historyIndex<=0;$('redoBtn').disabled=historyIndex>=history.length-1;}function updateStats(){stats.textContent=`${objectCount()} objetos • ${map.enemies.length} inimigos • ${gridCols()}×${gridRows()}`;}function commit(){if(historyLock)return;try{assertMapInputLimits(map);}catch(e){setStatus('Alteração não registrada: '+e.message);updateStats();return;}const s=snapshot();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);if(history.length>80)history.shift();else historyIndex++;if(history.length===80)historyIndex=79;safeAutosave();updateHistoryButtons();updateStats();}function resetHistory(){history=[snapshot()];historyIndex=0;updateHistoryButtons();safeAutosave();updateStats();}function restoreSnapshot(s){historyLock=true;try{normalizeMap(parseMapJson(s));syncDocumentControls();clearPending();clearSelection();draw();updateStats();}finally{historyLock=false;}}function undo(){if(historyIndex<=0)return;historyIndex--;restoreSnapshot(history[historyIndex]);updateHistoryButtons();setStatus('Desfeito.');}function redo(){if(historyIndex>=history.length-1)return;historyIndex++;restoreSnapshot(history[historyIndex]);updateHistoryButtons();setStatus('Refeito.');}function objectCount(){return map.walls.length+map.enemies.length+map.portals.length+map.checkpoints.length+map.keyDoors.length+map.buttons.length+map.coins.length+2;}


/* src/editor/selection.js */
'use strict';

function clearSelection(){
  selected=null; appendRouteTarget=null; routeDrag=null;
  props.classList.add('hidden'); emptySelection.classList.remove('hidden');
  wallProps.classList.add('hidden'); enemyProps.classList.add('hidden');
  staticProps.classList.add('hidden'); regularProps.classList.add('hidden'); guidedProps.classList.add('hidden');
}
function toggleModeFields(){const free=editMoveMode.value==='free';$('patrolCoords').classList.toggle('hidden',free);freeAngle.classList.toggle('hidden',!free);}
editMoveMode.addEventListener('change',toggleModeFields);
function showProperties(){
  if(!selected)return clearSelection();
  props.classList.remove('hidden');emptySelection.classList.add('hidden');
  wallProps.classList.add('hidden');enemyProps.classList.add('hidden');staticProps.classList.add('hidden');regularProps.classList.add('hidden');guidedProps.classList.add('hidden');
  if(selected.kind==='wall'){const w=map.walls.find(q=>q.id===selected.id);if(!w)return clearSelection();selectedInfo.textContent=`Parede #${w.id} • ${w.w}×${w.h}`;wallW.max=gridCols()-w.c;wallH.max=gridRows()-w.r;wallW.value=w.w;wallH.value=w.h;wallProps.classList.remove('hidden');return;}
  const e=map.enemies.find(q=>q.id===selected.id);if(!e)return clearSelection();enemyProps.classList.remove('hidden');selectedInfo.textContent=`Inimigo #${e.id} • ${e.type==='guided'?'guiado':e.type==='static'?'parado':'móvel'}`;
  if(e.type==='static')staticProps.classList.remove('hidden');
  else if(e.type==='guided'){guidedProps.classList.remove('hidden');guidedSpeed.value=e.speed;routeInfo.textContent=`Rota com ${e.route.length} ponto(s). Clique e arraste os pontos numerados para reposicioná-los.`;$('removeRouteBtn').disabled=e.route.length<=2;}
  else{regularProps.classList.remove('hidden');editEnemySpeed.value=e.speed;editMoveMode.value=e.mode||'patrol';startX.value=Math.round(e.start.x);startY.value=Math.round(e.start.y);endX.value=Math.round(e.end.x);endY.value=Math.round(e.end.y);freeAngleInput.value=Math.round(e.angle||0);toggleModeFields();}
}
function selectAt(p){const w=wallAt(p.c,p.r);if(w){selected={kind:'wall',id:w.id};showProperties();draw();return;}const e=enemyAtPoint(p.x,p.y);if(e){selected={kind:'enemy',id:e.id};showProperties();draw();return;}clearSelection();draw();}
$('applyWall').onclick=()=>{if(selected?.kind!=='wall')return;const w=map.walls.find(q=>q.id===selected.id);if(!w)return;w.w=clamp(Number(wallW.value)||1,1,gridCols()-w.c);w.h=clamp(Number(wallH.value)||1,1,gridRows()-w.r);commit();showProperties();draw();setStatus('Parede atualizada.');};
$('applyEnemy').onclick=()=>{if(selected?.kind!=='enemy')return;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='moving')return;e.speed=clamp(Number(editEnemySpeed.value)||1,1,1000);enemySpeed.value=e.speed;const requested=editMoveMode.value;if(requested==='free'&&map.walls.length){editMoveMode.value='patrol';toggleModeFields();setStatus('Modo livre bloqueado: o mapa possui paredes.');return;}e.mode=requested;if(e.mode==='patrol'){e.start=clampPointToCanvas({x:Number(startX.value)||0,y:Number(startY.value)||0});e.end=clampPointToCanvas({x:Number(endX.value)||0,y:Number(endY.value)||0});}else e.angle=normAngle(freeAngleInput.value);commit();showProperties();draw();setStatus('Inimigo atualizado.');};
$('applyGuided').onclick=()=>{if(selected?.kind!=='enemy')return;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='guided')return;e.speed=clamp(Number(guidedSpeed.value)||1,1,1000);enemySpeed.value=e.speed;commit();showProperties();setStatus('Velocidade da rota atualizada.');};
$('appendRouteBtn').onclick=()=>{if(selected?.kind!=='enemy')return;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='guided')return;appendRouteTarget=e.id;setStatus('Clique no mapa para adicionar um ponto à rota.');};
$('removeRouteBtn').onclick=()=>{if(selected?.kind!=='enemy')return;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='guided'||e.route.length<=2)return;e.route.pop();commit();showProperties();draw();setStatus('Último ponto removido.');};
$('reverseRouteBtn').onclick=()=>{if(selected?.kind!=='enemy')return;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='guided')return;e.route.reverse();commit();showProperties();draw();setStatus('Rota invertida.');};
$('deleteSelected').onclick=deleteSelected;
function deleteSelected(){if(!selected)return;const {kind,id}=selected;if(kind==='wall'){map.walls=map.walls.filter(q=>q.id!==id);map.buttons=map.buttons.filter(b=>!(b.target?.kind==='wall'&&b.target.id===id));}else{map.enemies=map.enemies.filter(q=>q.id!==id);map.buttons=map.buttons.filter(b=>!(b.target?.kind==='enemy'&&b.target.id===id));}clearSelection();commit();draw();setStatus('Objeto excluído.');}


/* src/editor/tools.js */
'use strict';
function resolveTarget(c,r,x,y){const w=wallAt(c,r);if(w)return{kind:'wall',id:w.id};const e=enemyAtPoint(x,y);if(e)return{kind:'enemy',id:e.id};const kd=map.keyDoors.find(k=>sameCell(k.door,c,r));if(kd)return{kind:'door',id:kd.id};return null;}
function occupied(c,r){return sameCell(map.spawn,c,r)||sameCell(map.goal,c,r)||!!wallAt(c,r)||map.checkpoints.some(q=>sameCell(q,c,r))||map.coins.some(q=>sameCell(q,c,r))||map.buttons.some(q=>sameCell(q.pos,c,r))||map.keyDoors.some(k=>sameCell(k.key,c,r)||sameCell(k.door,c,r))||map.portals.some(p=>sameCell(p.a,c,r)||sameCell(p.b,c,r));}
function removeAt(p){const wallIds=map.walls.filter(w=>wallContains(w,p.c,p.r)).map(w=>w.id);const enemyIds=map.enemies.filter(e=>{const a=enemyAnchor(e);return a&&pointInCell(a.x,a.y,p.c,p.r);}).map(e=>e.id);const doorIds=map.keyDoors.filter(k=>sameCell(k.key,p.c,p.r)||sameCell(k.door,p.c,p.r)).map(k=>k.id);map.walls=map.walls.filter(w=>!wallIds.includes(w.id));map.enemies=map.enemies.filter(e=>!enemyIds.includes(e.id));map.checkpoints=map.checkpoints.filter(q=>!sameCell(q,p.c,p.r));map.coins=map.coins.filter(q=>!sameCell(q,p.c,p.r));map.portals=map.portals.filter(q=>!(sameCell(q.a,p.c,p.r)||sameCell(q.b,p.c,p.r)));map.keyDoors=map.keyDoors.filter(k=>!doorIds.includes(k.id));map.buttons=map.buttons.filter(b=>{if(sameCell(b.pos,p.c,p.r))return false;return!(wallIds.includes(b.target?.id)||enemyIds.includes(b.target?.id)||doorIds.includes(b.target?.id));});clearSelection();}
function clearPendingExcept(k=''){if(k!=='portal')pendingPortal=null;if(k!=='keydoor')pendingKey=null;if(k!=='button')pendingButton=null;if(!['horizontal','vertical','directional'].includes(k))pendingPatrol=null;if(k!=='guided')pendingGuide=null;appendRouteTarget=null;updateGuideButtons();}function clearPending(){clearPendingExcept('');}function updateGuideButtons(){const on=!!pendingGuide;finishGuideBtn.disabled=!on;cancelGuideBtn.disabled=!on;}
function pointerPos(ev){const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width,sy=canvas.height/rect.height;const x=clamp((ev.clientX-rect.left)*sx,0,Math.max(0,canvas.width-.001)),y=clamp((ev.clientY-rect.top)*sy,0,Math.max(0,canvas.height-.001));return{x,y,c:Math.floor(x/CELL),r:Math.floor(y/CELL)};}
function findRouteNode(p){if(selected?.kind!=='enemy')return null;const e=map.enemies.find(q=>q.id===selected.id);if(!e||e.type!=='guided')return null;let best=null,bestD=12;e.route.forEach((q,i)=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<=bestD){best={enemy:e,index:i};bestD=d;}});return best;}
function place(p){
if(tool==='select')return selectAt(p);if(tool==='erase'){removeAt(p);commit();draw();return;}if(tool==='spawn'){removeAt(p);map.spawn={c:p.c,r:p.r};commit();draw();return;}if(tool==='goal'){removeAt(p);map.goal={c:p.c,r:p.r};commit();draw();return;}
if(tool==='portal'){if(!pendingPortal){removeAt(p);pendingPortal={c:p.c,r:p.r};setStatus('Portal: escolha a segunda ponta.');}else if(!sameCell(pendingPortal,p.c,p.r)){if(!canAddToCollection('portals'))return;removeAt(p);map.portals.push({id:nextId(map.portals),a:{...pendingPortal},b:{c:p.c,r:p.r}});pendingPortal=null;commit();updateStatus();}draw();return;}
if(tool==='keydoor'){if(!pendingKey){removeAt(p);pendingKey={c:p.c,r:p.r};setStatus('Chave posicionada. Agora escolha a porta.');}else if(!sameCell(pendingKey,p.c,p.r)){if(!canAddToCollection('keyDoors'))return;removeAt(p);map.keyDoors.push({id:nextId(map.keyDoors),key:{...pendingKey},door:{c:p.c,r:p.r}});pendingKey=null;commit();updateStatus();}draw();return;}
if(tool==='button'){if(!pendingButton){if(occupied(p.c,p.r))removeAt(p);pendingButton={c:p.c,r:p.r};setStatus('Botão posicionado. Clique em parede, inimigo ou porta.');}else{const target=resolveTarget(p.c,p.r,p.x,p.y);if(!target){setStatus('Alvo inválido. Escolha parede, inimigo ou porta.');return;}if(!canAddToCollection('buttons'))return;map.buttons.push({id:nextId(map.buttons),pos:{...pendingButton},target});pendingButton=null;commit();updateStatus();}draw();return;}
if(['horizontal','vertical','directional'].includes(tool)){let q=snapPoint(p);if(!pendingPatrol){pendingPatrol={tool,start:q};setStatus('Patrulha: agora escolha o ponto Y.');draw();return;}if(tool==='horizontal')q={x:q.x,y:pendingPatrol.start.y};if(tool==='vertical')q={x:pendingPatrol.start.x,y:q.y};if(Math.hypot(q.x-pendingPatrol.start.x,q.y-pendingPatrol.start.y)<1){setStatus('O ponto Y precisa ser diferente do X.');return;}if(!canAddToCollection('enemies'))return;map.enemies.push({id:nextId(map.enemies),type:'moving',mode:'patrol',speed:clamp(Number(enemySpeed.value)||90,1,1000),start:{...pendingPatrol.start},end:q,angle:0});pendingPatrol=null;commit();draw();updateStatus();return;}
if(tool==='guided'){const q=snapPoint(p);if(!pendingGuide)pendingGuide=[q];else{if(pendingGuide.length>=SECURITY.MAX_ROUTE_POINTS_PER_ENEMY){setStatus(`Rota limitada a ${SECURITY.MAX_ROUTE_POINTS_PER_ENEMY} pontos.`);return;}pendingGuide.push(q);}updateGuideButtons();updateStatus();draw();return;}
if(sameCell(map.spawn,p.c,p.r)||sameCell(map.goal,p.c,p.r))return;removeAt(p);if(tool==='wall'&&canAddToCollection('walls'))map.walls.push({id:nextId(map.walls),c:p.c,r:p.r,w:1,h:1});if(tool==='static'&&canAddToCollection('enemies'))map.enemies.push({id:nextId(map.enemies),type:'static',x:(p.c+.5)*CELL,y:(p.r+.5)*CELL});if(tool==='checkpoint'&&canAddToCollection('checkpoints'))map.checkpoints.push({id:nextId(map.checkpoints),c:p.c,r:p.r});if(tool==='coin'&&canAddToCollection('coins'))map.coins.push({id:nextId(map.coins),c:p.c,r:p.r});commit();draw();}
finishGuideBtn.onclick=()=>{if(!pendingGuide)return;if(pendingGuide.length<2){setStatus('A rota guiada precisa de pelo menos 2 pontos.');return;}if(!canAddToCollection('enemies'))return;map.enemies.push({id:nextId(map.enemies),type:'guided',speed:clamp(Number(enemySpeed.value)||90,1,1000),route:pendingGuide.map(p=>({...p}))});pendingGuide=null;updateGuideButtons();commit();draw();updateStatus();};cancelGuideBtn.onclick=()=>{pendingGuide=null;updateGuideButtons();draw();updateStatus();};
canvas.addEventListener('pointerdown',ev=>{if(mode!=='edit')return;const p=pointerPos(ev);dragging=true;canvas.setPointerCapture(ev.pointerId);if(tool==='select'&&appendRouteTarget){const e=map.enemies.find(q=>q.id===appendRouteTarget&&q.type==='guided');if(e){if(e.route.length>=SECURITY.MAX_ROUTE_POINTS_PER_ENEMY){appendRouteTarget=null;setStatus(`Rota limitada a ${SECURITY.MAX_ROUTE_POINTS_PER_ENEMY} pontos.`);return;}e.route.push(snapPoint(p));appendRouteTarget=null;commit();showProperties();draw();setStatus('Ponto adicionado à rota.');}return;}if(tool==='select'){const node=findRouteNode(p);if(node){routeDrag={enemyId:node.enemy.id,index:node.index};return;}}place(p);});
canvas.addEventListener('pointermove',ev=>{const p=pointerPos(ev);cursorLabel.textContent=`x: ${Math.round(p.x)} • y: ${Math.round(p.y)}`;if(mode!=='edit'||!dragging)return;if(routeDrag){const e=map.enemies.find(q=>q.id===routeDrag.enemyId&&q.type==='guided');if(e){e.route[routeDrag.index]=snapPoint(p);draw();}return;}if(['wall','erase'].includes(tool))place(p);});function endPointer(){dragging=false;if(routeDrag){routeDrag=null;commit();showProperties();setStatus('Ponto da rota movido.');}}canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);
document.querySelectorAll('.tool').forEach(btn=>btn.onclick=()=>{tool=btn.dataset.tool;clearPendingExcept(tool);clearSelection();document.querySelectorAll('.tool').forEach(b=>b.classList.remove('active'));btn.classList.add('active');updateStatus();draw();});


/* src/ui/inspector.js */
'use strict';
function syncDocumentControls(){levelName.value=map.meta?.name||'Nova fase';resetCollectibles.checked=!!map.settings.resetCollectiblesOnDeath;resetLogic.checked=!!map.settings.resetLogicOnDeath;resetEnemies.checked=!!map.settings.resetEnemiesOnDeath;mapColsInput.value=gridCols();mapRowsInput.value=gridRows();}
function syncLevelNameFromInput({finalize=false}={}){let name=cleanText(levelName.value,SECURITY.MAX_LEVEL_NAME,'');if(finalize&&!name)name='Nova fase';if(finalize||levelName.value.length>SECURITY.MAX_LEVEL_NAME)levelName.value=name||'Nova fase';map.meta.name=name||'Nova fase';safeAutosave();return map.meta.name;}
levelName.addEventListener('input',()=>syncLevelNameFromInput());levelName.addEventListener('change',()=>{syncLevelNameFromInput({finalize:true});commit();});resetCollectibles.onchange=()=>{map.settings.resetCollectiblesOnDeath=resetCollectibles.checked;commit();};resetLogic.onchange=()=>{map.settings.resetLogicOnDeath=resetLogic.checked;commit();};resetEnemies.onchange=()=>{map.settings.resetEnemiesOnDeath=resetEnemies.checked;commit();};
$('applyMapSize').onclick=()=>{const newCols=clamp(Number(mapColsInput.value)||30,10,120),newRows=clamp(Number(mapRowsInput.value)||18,8,80),shrinking=newCols<gridCols()||newRows<gridRows();if(shrinking&&!confirm('Diminuir o mapa pode remover ou ajustar objetos fora da nova área. Deseja continuar?')){syncDocumentControls();return;}map.grid.cols=newCols;map.grid.rows=newRows;resizeCanvas();fitMapToGrid();clearSelection();commit();draw();setStatus(`Mapa redimensionado para ${newCols}×${newRows}.`);};


/* src/game/collision.js */
'use strict';
function rectWall(w){return{x:w.c*CELL,y:w.r*CELL,w:w.w*CELL,h:w.h*CELL};}function rectCell(c,r){return{x:c*CELL,y:r*CELL,w:CELL,h:CELL};}function circleRect(cx,cy,r,q){const nx=Math.max(q.x,Math.min(cx,q.x+q.w)),ny=Math.max(q.y,Math.min(cy,q.y+q.h)),dx=cx-nx,dy=cy-ny;return dx*dx+dy*dy<r*r;}function circleCircle(a,b){const dx=a.x-b.x,dy=a.y-b.y,rr=(a.r||9)+(b.r||9);return dx*dx+dy*dy<rr*rr;}function doorOpen(id){return collectedKeys.has(id)||disabledTargets.has('door:'+id);}function wallActive(id){return!disabledTargets.has('wall:'+id);}function enemyActive(id){return!disabledTargets.has('enemy:'+id);}function playerBlocked(x,y,r){if(x-r<0||y-r<0||x+r>canvas.width||y+r>canvas.height)return true;for(const w of map.walls)if(wallActive(w.id)&&circleRect(x,y,r,rectWall(w)))return true;for(const kd of map.keyDoors)if(!doorOpen(kd.id)&&circleRect(x,y,r,rectCell(kd.door.c,kd.door.r)))return true;return false;}


/* src/game/enemies.js */
'use strict';
function buildSimEnemies(){return map.enemies.map(e=>{if(e.type==='static')return{id:e.id,type:'static',x:e.x,y:e.y,r:9};if(e.type==='guided')return{id:e.id,type:'guided',x:e.route[0].x,y:e.route[0].y,r:9,speed:e.speed,route:e.route.map(p=>({...p})),next:1};if(e.mode==='free'){const rad=normAngle(e.angle)*Math.PI/180;return{id:e.id,type:'moving',mode:'free',x:e.start.x,y:e.start.y,r:9,speed:e.speed,angle:e.angle,vx:Math.cos(rad)*e.speed,vy:Math.sin(rad)*e.speed};}return{id:e.id,type:'moving',mode:'patrol',x:e.start.x,y:e.start.y,r:9,speed:e.speed,start:{...e.start},end:{...e.end},target:1};});}
function moveTowardBudget(e,t,remaining){const dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy);if(d<.001){e.x=t.x;e.y=t.y;return{reached:true,remaining};}if(remaining>=d){e.x=t.x;e.y=t.y;return{reached:true,remaining:remaining-d};}e.x+=dx/d*remaining;e.y+=dy/d*remaining;return{reached:false,remaining:0};}
function updateGuidedEnemy(e,dt){if(e.route.length<2)return;let remaining=e.speed*dt,guard=0;while(remaining>.0001&&guard++<128){const t=e.route[e.next%e.route.length],step=moveTowardBudget(e,t,remaining);remaining=step.remaining;if(!step.reached)break;e.next=(e.next+1)%e.route.length;}}
function updatePatrolEnemy(e,dt){let remaining=e.speed*dt,guard=0;while(remaining>.0001&&guard++<128){const t=e.target===1?e.end:e.start,step=moveTowardBudget(e,t,remaining);remaining=step.remaining;if(!step.reached)break;e.target=e.target===1?0:1;}}
function updateEnemy(e,dt){if(e.type==='static')return;if(e.type==='guided'){updateGuidedEnemy(e,dt);return;}if(e.mode==='patrol'){updatePatrolEnemy(e,dt);return;}if(e.mode==='free'){e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x-e.r<0){e.x=e.r;e.vx=Math.abs(e.vx);}if(e.x+e.r>canvas.width){e.x=canvas.width-e.r;e.vx=-Math.abs(e.vx);}if(e.y-e.r<0){e.y=e.r;e.vy=Math.abs(e.vy);}if(e.y+e.r>canvas.height){e.y=canvas.height-e.r;e.vy=-Math.abs(e.vy);}}}


/* src/game/player.js */
'use strict';
function movePlayer(dx,dy){let ox=player.x,oy=player.y;player.x+=dx;if(playerBlocked(player.x,player.y,player.r))player.x=ox;player.y+=dy;if(playerBlocked(player.x,player.y,player.r))player.y=oy;}
function portalCircle(pos){const p=cellCenter(pos.c,pos.r);return{x:p.x,y:p.y,r:12};}function touchingPortal(o){return map.portals.some(p=>circleCircle(o,portalCircle(p.a))||circleCircle(o,portalCircle(p.b)));}function teleport(){if(player.portalLock){if(touchingPortal(player))return;player.portalLock=false;}for(const p of map.portals){const a=portalCircle(p.a),b=portalCircle(p.b);if(circleCircle(player,a)){player.x=b.x;player.y=b.y;player.portalLock=true;return;}if(circleCircle(player,b)){player.x=a.x;player.y=a.y;player.portalLock=true;return;}}}
function collect(){for(const c of map.coins){if(collectedCoins.has(c.id))continue;const p=cellCenter(c.c,c.r);if(circleCircle(player,{x:p.x,y:p.y,r:8}))collectedCoins.add(c.id);}for(const kd of map.keyDoors){if(collectedKeys.has(kd.id))continue;const p=cellCenter(kd.key.c,kd.key.r);if(circleCircle(player,{x:p.x,y:p.y,r:9}))collectedKeys.add(kd.id);}}
function checkpoint(){for(const cp of map.checkpoints)if(circleRect(player.x,player.y,player.r,rectCell(cp.c,cp.r))&&activeCheckpoint!==cp.id){activeCheckpoint=cp.id;respawnPoint=cellCenter(cp.c,cp.r);}}
function toggleTarget(t){const k=targetKey(t);if(!k)return;disabledTargets.has(k)?disabledTargets.delete(k):disabledTargets.add(k);}function buttons(){for(const b of map.buttons){const k='b:'+b.id,inside=circleRect(player.x,player.y,player.r,rectCell(b.pos.c,b.pos.r));if(inside&&!buttonInside.has(k)){buttonInside.add(k);toggleTarget(b.target);}else if(!inside)buttonInside.delete(k);}}
function respawn(){deaths++;if(map.settings.resetCollectiblesOnDeath){collectedCoins=new Set();collectedKeys=new Set();}if(map.settings.resetLogicOnDeath){disabledTargets=new Set();buttonInside=new Set();}if(map.settings.resetEnemiesOnDeath)simEnemies=buildSimEnemies();player.x=respawnPoint.x;player.y=respawnPoint.y;player.portalLock=false;}


/* src/game/runtime.js */
'use strict';
function setMode(next){mode=next;$('editBtn').classList.toggle('active',next==='edit');$('testBtn').classList.toggle('active',next==='test');modeLabel.textContent=next==='edit'?'EDIÇÃO':'TESTE';clearSelection();if(next==='test')startTest();else{if(raf)cancelAnimationFrame(raf);raf=null;player=null;simEnemies=[];won=false;updateStatus();draw();}}
function startTest(){if(raf)cancelAnimationFrame(raf);won=false;collectedCoins=new Set();collectedKeys=new Set();disabledTargets=new Set();buttonInside=new Set();activeCheckpoint=null;respawnPoint=cellCenter(map.spawn.c,map.spawn.r);player={x:respawnPoint.x,y:respawnPoint.y,r:10,speed:175,portalLock:false};simEnemies=buildSimEnemies();last=performance.now();updateStatus();raf=requestAnimationFrame(loop);}
function update(dt){if(!player||won)return;let dx=0,dy=0;if(keys.w||keys.arrowup)dy--;if(keys.s||keys.arrowdown)dy++;if(keys.a||keys.arrowleft)dx--;if(keys.d||keys.arrowright)dx++;if(dx&&dy){dx*=.70710678;dy*=.70710678;}movePlayer(dx*player.speed*dt,0);movePlayer(0,dy*player.speed*dt);teleport();collect();checkpoint();buttons();for(const e of simEnemies){if(!enemyActive(e.id))continue;updateEnemy(e,dt);if(circleCircle(player,e)){respawn();break;}}if(circleRect(player.x,player.y,player.r,rectCell(map.goal.c,map.goal.r))){if(collectedCoins.size>=map.coins.length){won=true;updateStatus();}else setStatus(`Chegada bloqueada: faltam ${map.coins.length-collectedCoins.size} moeda(s).`);}}
function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;update(dt);draw();raf=requestAnimationFrame(loop);}


/* src/render/renderer.js */
'use strict';
function setStatus(s){status.textContent=s;}function updateStatus(){if(mode==='edit'){const names={select:'Selecionar / editar',wall:'Parede',spawn:'Início',goal:'Chegada',checkpoint:'Checkpoint',static:'Inimigo parado',horizontal:'Patrulha horizontal',vertical:'Patrulha vertical',directional:'Patrulha X↔Y',guided:'Inimigo guiado',portal:'Portal',keydoor:'Chave + porta',button:'Botão → objeto',coin:'Moeda',erase:'Apagar'};let tail='';if(pendingPatrol)tail=' • escolha o ponto Y';if(pendingGuide)tail=` • ${pendingGuide.length} ponto(s) na rota`;setStatus(`Ferramenta: ${names[tool]}${tail}`);}else setStatus(won?`Fase concluída • ${deaths} morte(s)`:`Teste • ${deaths} morte(s) • moedas ${collectedCoins.size}/${map.coins.length}${activeCheckpoint?' • CP '+activeCheckpoint:''}`);}
function grid(){ctx.strokeStyle='#dedede';ctx.lineWidth=1;for(let c=0;c<=gridCols();c++){ctx.beginPath();ctx.moveTo(c*CELL,0);ctx.lineTo(c*CELL,canvas.height);ctx.stroke();}for(let r=0;r<=gridRows();r++){ctx.beginPath();ctx.moveTo(0,r*CELL);ctx.lineTo(canvas.width,r*CELL);ctx.stroke();}}
function circle(x,y,r,fill,stroke='#111',lw=2){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke();}function line(points,color='#6b28a8',dash=[]){if(points.length<2)return;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.stroke();ctx.restore();}
function drawRouteNodes(e){if(e.type!=='guided')return;e.route.forEach((p,i)=>{circle(p.x,p.y,i===0?8:5,i===0?'#8c3fd1':'#d7b0ee','#5b207e',1);ctx.fillStyle='#45205d';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),p.x,p.y);});}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f4f4f4';ctx.fillRect(0,0,canvas.width,canvas.height);grid();ctx.fillStyle='#91e57c';ctx.fillRect(map.goal.c*CELL,map.goal.r*CELL,CELL,CELL);
for(const cp of map.checkpoints){const r=rectCell(cp.c,cp.r);ctx.fillStyle=mode==='test'&&activeCheckpoint===cp.id?'#d7ed75':'#e8efaa';ctx.fillRect(r.x,r.y,r.w,r.h);}
for(const w of map.walls){if(mode==='test'&&!wallActive(w.id))continue;const r=rectWall(w);ctx.fillStyle='#9a96c9';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#716d97';ctx.lineWidth=1;ctx.strokeRect(r.x+.5,r.y+.5,r.w-1,r.h-1);}
for(const kd of map.keyDoors){const kp=cellCenter(kd.key.c,kd.key.r),dr=rectCell(kd.door.c,kd.door.r);if(mode==='edit'||!collectedKeys.has(kd.id))circle(kp.x,kp.y,9,'#ffd54a','#8d6500');if(mode==='edit'||!doorOpen(kd.id)){ctx.fillStyle='#7356b8';ctx.fillRect(dr.x+3,dr.y+2,dr.w-6,dr.h-4);}}
for(const p of map.portals)for(const q of[p.a,p.b]){const z=cellCenter(q.c,q.r);circle(z.x,z.y,12,'#f39a34','#a85400',3);circle(z.x,z.y,6,'#4a2410','#ffbd66',1);}if(mode==='edit'&&pendingPortal){const z=cellCenter(pendingPortal.c,pendingPortal.r);circle(z.x,z.y,12,'#ffc078','#a85400',2);}
for(const b of map.buttons){const r=rectCell(b.pos.c,b.pos.r);ctx.fillStyle=mode==='test'&&disabledTargets.has(targetKey(b.target))?'#54777d':'#69d2dc';ctx.fillRect(r.x+5,r.y+5,r.w-10,r.h-10);}for(const c of map.coins){if(mode==='test'&&collectedCoins.has(c.id))continue;const p=cellCenter(c.c,c.r);circle(p.x,p.y,8,'#f6c945','#8d6500');}
if(mode==='edit'){for(const e of map.enemies){if(e.type==='moving'){if(e.mode==='patrol'){line([e.start,e.end],'#d34a4a',[6,4]);circle(e.start.x,e.start.y,9,'#e43d3d');circle(e.end.x,e.end.y,4,'#ffb0b0','#9b2020',1);}else circle(e.start.x,e.start.y,9,'#e43d3d');}else if(e.type==='guided'){line(e.route,'#8d3cc6',[5,4]);drawRouteNodes(e);}else circle(e.x,e.y,9,'#e43d3d');}const s=cellCenter(map.spawn.c,map.spawn.r);circle(s.x,s.y,10,'#2b63ff');if(pendingPatrol)circle(pendingPatrol.start.x,pendingPatrol.start.y,9,'#e43d3d');if(pendingGuide){line(pendingGuide,'#8d3cc6',[5,4]);pendingGuide.forEach((p,i)=>circle(p.x,p.y,i===0?8:5,i===0?'#8c3fd1':'#d7b0ee','#5b207e',1));}if(selected){if(selected.kind==='wall'){const w=map.walls.find(q=>q.id===selected.id);if(w){const r=rectWall(w);ctx.save();ctx.strokeStyle='#00a6ff';ctx.lineWidth=3;ctx.setLineDash([7,4]);ctx.strokeRect(r.x+2,r.y+2,r.w-4,r.h-4);ctx.restore();}}else{const e=map.enemies.find(q=>q.id===selected.id);if(e){const p=enemyAnchor(e);ctx.save();ctx.strokeStyle='#00a6ff';ctx.lineWidth=3;ctx.setLineDash([7,4]);ctx.strokeRect(p.x-14,p.y-14,28,28);ctx.restore();if(e.type==='guided')drawRouteNodes(e);}}}}else{for(const e of simEnemies)if(enemyActive(e.id))circle(e.x,e.y,e.r,e.type==='guided'?'#8c3fd1':'#e43d3d');if(player)circle(player.x,player.y,player.r,'#2b63ff');}
if(won){ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.font='bold 38px Segoe UI,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('FASE CONCLUÍDA',canvas.width/2,canvas.height/2-10);ctx.font='18px Segoe UI,Arial';ctx.fillText(`${deaths} morte(s) • ${collectedCoins.size}/${map.coins.length} moedas`,canvas.width/2,canvas.height/2+28);}}


/* src/editor/clipboard.js */
'use strict';
function selectionKey(s){return s?`${s.kind}:${s.id}`:'';}function selectionArray(){if(selectedItems.length)return selectedItems.slice();return selected?[selected]:[];}function isSelectedItem(kind,id){return selectionArray().some(s=>s.kind===kind&&s.id===id);}function resetSelectionGroup(){selectedItems=selected?[selected]:[];}
const __oldClearSelection=clearSelection;clearSelection=function(){__oldClearSelection();selectedItems=[];selectionRect=null;selectionStart=null;};
function ensurePrimarySelection(){const arr=selectionArray();selected=arr[0]||null;if(selected)selectedItems=arr;}
function getObject(sel){if(!sel)return null;if(sel.kind==='wall')return map.walls.find(q=>q.id===sel.id)||null;if(sel.kind==='enemy')return map.enemies.find(q=>q.id===sel.id)||null;return null;}
function normalizeSelectionGroup(){const arr=selectionArray().filter(s=>!!getObject(s)),uniq=[],seen=new Set();for(const s of arr){const k=selectionKey(s);if(!seen.has(k)){seen.add(k);uniq.push(s);}}selectedItems=uniq;selected=uniq[0]||null;}
const __oldShowProperties=showProperties;showProperties=function(){normalizeSelectionGroup();const arr=selectionArray();if(arr.length<=1)return __oldShowProperties();props.classList.remove('hidden');emptySelection.classList.add('hidden');wallProps.classList.add('hidden');enemyProps.classList.add('hidden');staticProps.classList.add('hidden');regularProps.classList.add('hidden');guidedProps.classList.add('hidden');selectedInfo.textContent=`${arr.length} itens selecionados`;};
selectAt=function(p){const w=wallAt(p.c,p.r),e=enemyAtPoint(p.x,p.y),hit=w?{kind:'wall',id:w.id}:e?{kind:'enemy',id:e.id}:null;if(selectToggleMode){if(hit){const k=selectionKey(hit),idx=selectionArray().findIndex(s=>selectionKey(s)===k);if(idx>=0)selectedItems=selectionArray().filter((_,i)=>i!==idx);else{selectedItems=selectionArray().concat([hit]);selected=hit;}ensurePrimarySelection();if(selected)showProperties();else clearSelection();draw();}else draw();return;}if(hit){selected=hit;selectedItems=[hit];showProperties();draw();return;}clearSelection();draw();};
function deleteSelectionSet(arr){const wallIds=new Set(arr.filter(s=>s.kind==='wall').map(s=>s.id)),enemyIds=new Set(arr.filter(s=>s.kind==='enemy').map(s=>s.id));if(wallIds.size)map.walls=map.walls.filter(q=>!wallIds.has(q.id));if(enemyIds.size)map.enemies=map.enemies.filter(q=>!enemyIds.has(q.id));map.buttons=map.buttons.filter(b=>!((b.target?.kind==='wall'&&wallIds.has(b.target.id))||(b.target?.kind==='enemy'&&enemyIds.has(b.target.id))));}
const __oldDeleteSelected=deleteSelected;deleteSelected=function(){const arr=selectionArray();if(!arr.length)return __oldDeleteSelected();deleteSelectionSet(arr);clearSelection();commit();draw();setStatus(arr.length>1?`${arr.length} objetos excluídos.`:'Objeto excluído.');};$('deleteSelected').onclick=deleteSelected;
function cloneWall(w){return{kind:'wall',data:cloneJson(w)};}function cloneEnemy(e){return{kind:'enemy',data:cloneJson(e)};}function cloneSelection(){const out=[];for(const s of selectionArray()){const obj=getObject(s);if(!obj)continue;out.push(s.kind==='wall'?cloneWall(obj):cloneEnemy(obj));}return out;}
function shiftEnemy(enemy,dx=CELL,dy=CELL){if(enemy.type==='static'){enemy.x+=dx;enemy.y+=dy;}else if(enemy.type==='guided')enemy.route=enemy.route.map(p=>({x:p.x+dx,y:p.y+dy}));else{enemy.start={x:enemy.start.x+dx,y:enemy.start.y+dy};enemy.end={x:enemy.end.x+dx,y:enemy.end.y+dy};}}
function clampWallObj(w){w.c=clamp(w.c,0,gridCols()-1);w.r=clamp(w.r,0,gridRows()-1);w.w=clamp(w.w,1,gridCols()-w.c);w.h=clamp(w.h,1,gridRows()-w.r);}function clampEnemyObj(e){if(e.type==='static'){const p=clampPointToCanvas({x:e.x,y:e.y});e.x=p.x;e.y=p.y;}else if(e.type==='guided')e.route=(e.route||[]).map(clampPointToCanvas);else{e.start=clampPointToCanvas(e.start);e.end=clampPointToCanvas(e.end);}}
function pasteClipboard(offsetMultiplier=1){if(!clipboardItems.length){setStatus('Nada copiado.');return;}const newSel=[];for(const item of clipboardItems){if(item.kind==='wall'){if(!canAddToCollection('walls'))break;const w=cloneJson(item.data);w.id=nextId(map.walls);w.c+=offsetMultiplier;w.r+=offsetMultiplier;clampWallObj(w);map.walls.push(w);newSel.push({kind:'wall',id:w.id});}else if(item.kind==='enemy'){if(!canAddToCollection('enemies'))break;const e=cloneJson(item.data);e.id=nextId(map.enemies);shiftEnemy(e,CELL*offsetMultiplier,CELL*offsetMultiplier);clampEnemyObj(e);map.enemies.push(e);newSel.push({kind:'enemy',id:e.id});}}selectedItems=newSel;selected=newSel[0]||null;commit();showProperties();draw();setStatus(`${newSel.length} item(ns) colado(s).`);}
function copySelectionToClipboard(){clipboardItems=cloneSelection();setStatus(clipboardItems.length?`${clipboardItems.length} item(ns) copiado(s).`:'Nenhum item selecionado para copiar.');}function duplicateSelection(){clipboardItems=cloneSelection();pasteClipboard(1);}
const __baseDraw=draw;draw=function(){__baseDraw();if(mode==='edit'){const arr=selectionArray();if(arr.length>1){ctx.save();ctx.strokeStyle='#00d4ff';ctx.lineWidth=2;ctx.setLineDash([6,4]);for(const s of arr){const obj=getObject(s);if(!obj)continue;if(s.kind==='wall'){const r=rectWall(obj);ctx.strokeRect(r.x+3,r.y+3,r.w-6,r.h-6);}else if(s.kind==='enemy'){const p=enemyAnchor(obj);if(p)ctx.strokeRect(p.x-14,p.y-14,28,28);}}ctx.restore();}if(selectionRect){const x=Math.min(selectionRect.x1,selectionRect.x2),y=Math.min(selectionRect.y1,selectionRect.y2),w=Math.abs(selectionRect.x2-selectionRect.x1),h=Math.abs(selectionRect.y2-selectionRect.y1);ctx.save();ctx.fillStyle='rgba(0,170,255,.10)';ctx.strokeStyle='rgba(0,170,255,.95)';ctx.setLineDash([8,5]);ctx.lineWidth=2;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.restore();}}};
duplicateBtn&&(duplicateBtn.onclick=duplicateSelection);copyBtn&&(copyBtn.onclick=copySelectionToClipboard);pasteBtn&&(pasteBtn.onclick=()=>pasteClipboard(1));duplicateSelectedBtn&&(duplicateSelectedBtn.onclick=duplicateSelection);copySelectedBtn&&(copySelectedBtn.onclick=copySelectionToClipboard);


/* src/editor/viewport.js */
'use strict';
function applyZoom(){canvas.style.width=`${Math.round(canvas.width*viewportZoom)}px`;canvas.style.height=`${Math.round(canvas.height*viewportZoom)}px`;if(zoomResetBtn)zoomResetBtn.textContent=`${Math.round(viewportZoom*100)}%`;}function setZoom(z){viewportZoom=clamp(z,.5,3);applyZoom();}zoomOutBtn&&(zoomOutBtn.onclick=()=>setZoom(viewportZoom-.1));zoomInBtn&&(zoomInBtn.onclick=()=>setZoom(viewportZoom+.1));zoomResetBtn&&(zoomResetBtn.onclick=()=>setZoom(1));applyZoom();
canvasWrap?.addEventListener('wheel',ev=>{if(!(ev.ctrlKey||ev.metaKey))return;ev.preventDefault();setZoom(viewportZoom+(ev.deltaY<0?.1:-.1));},{passive:false});addEventListener('keydown',ev=>{if(ev.code==='Space'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))spacePan=true;});addEventListener('keyup',ev=>{if(ev.code==='Space')spacePan=false;});
canvas.addEventListener('pointerdown',ev=>{selectToggleMode=!!(ev.ctrlKey||ev.metaKey||ev.shiftKey);if(mode!=='edit')return;if((ev.button===1||spacePan)&&canvasWrap){panState={x:ev.clientX,y:ev.clientY,sl:canvasWrap.scrollLeft,st:canvasWrap.scrollTop};ev.preventDefault();ev.stopPropagation();}else if(tool==='select'&&!selectToggleMode){const p=pointerPos(ev),w=wallAt(p.c,p.r),e=enemyAtPoint(p.x,p.y);if(!w&&!e){selectionStart=p;selectionRect={x1:p.x,y1:p.y,x2:p.x,y2:p.y};}}},true);
canvasWrap?.addEventListener('pointermove',ev=>{if(panState){canvasWrap.scrollLeft=panState.sl-(ev.clientX-panState.x);canvasWrap.scrollTop=panState.st-(ev.clientY-panState.y);}},true);addEventListener('pointerup',()=>{panState=null;selectToggleMode=false;});
canvas.addEventListener('pointermove',ev=>{if(selectionStart&&dragging&&tool==='select'&&mode==='edit'){const p=pointerPos(ev);selectionRect={x1:selectionStart.x,y1:selectionStart.y,x2:p.x,y2:p.y};draw();}},true);
canvas.addEventListener('pointerup',()=>{if(selectionStart&&selectionRect){const x1=Math.min(selectionRect.x1,selectionRect.x2),y1=Math.min(selectionRect.y1,selectionRect.y2),x2=Math.max(selectionRect.x1,selectionRect.x2),y2=Math.max(selectionRect.y1,selectionRect.y2),hits=[];for(const w of map.walls){const r=rectWall(w);if(r.x<x2&&r.x+r.w>x1&&r.y<y2&&r.y+r.h>y1)hits.push({kind:'wall',id:w.id});}for(const e of map.enemies){const p=enemyAnchor(e);if(p&&p.x>=x1&&p.x<=x2&&p.y>=y1&&p.y<=y2)hits.push({kind:'enemy',id:e.id});}if(hits.length){selectedItems=hits;selected=hits[0];showProperties();}else clearSelection();selectionStart=null;selectionRect=null;draw();}},true);
