/* src/editor/validation.js */
'use strict';
function validateMap(){const errors=[],warnings=[];try{assertMapInputLimits(map);}catch(e){errors.push('Limite de segurança: '+(e?.message||'mapa inválido.'));}if(!insideCell(map.spawn.c,map.spawn.r))errors.push('O ponto de início está fora do mapa.');if(!insideCell(map.goal.c,map.goal.r))errors.push('A chegada está fora do mapa.');const blocked=(c,r)=>!!wallAt(c,r)||map.keyDoors.some(k=>sameCell(k.door,c,r));if(blocked(map.spawn.c,map.spawn.r))errors.push('O início está bloqueado por uma parede ou porta.');if(blocked(map.goal.c,map.goal.r))warnings.push('A chegada está coberta por uma parede ou porta.');for(const e of map.enemies){if(e.type==='guided'&&(!Array.isArray(e.route)||e.route.length<2))errors.push(`Inimigo guiado #${e.id} precisa de pelo menos 2 pontos.`);if(e.type==='moving'&&Math.hypot(e.start.x-e.end.x,e.start.y-e.end.y)<1)warnings.push(`Inimigo móvel #${e.id} tem rota muito curta.`);}const cols=gridCols(),rows=gridRows(),passable=(c,r)=>c>=0&&r>=0&&c<cols&&r<rows&&!blocked(c,r),queue=[[map.spawn.c,map.spawn.r]],seen=new Set([`${map.spawn.c},${map.spawn.r}`]);while(queue.length){const [c,r]=queue.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nc=c+dx,nr=r+dy,k=`${nc},${nr}`;if(passable(nc,nr)&&!seen.has(k)){seen.add(k);queue.push([nc,nr]);}}for(const p of map.portals){let target=null;if(sameCell(p.a,c,r))target=p.b;else if(sameCell(p.b,c,r))target=p.a;if(target){const k=`${target.c},${target.r}`;if(passable(target.c,target.r)&&!seen.has(k)){seen.add(k);queue.push([target.c,target.r]);}}}}if(!seen.has(`${map.goal.c},${map.goal.r}`))warnings.push('A chegada não parece alcançável a partir do início (considerando paredes, portas fechadas e portais).');for(const cp of map.checkpoints)if(!seen.has(`${cp.c},${cp.r}`))warnings.push(`Checkpoint #${cp.id} pode estar inacessível.`);for(const coin of map.coins)if(!seen.has(`${coin.c},${coin.r}`))warnings.push(`Moeda #${coin.id} pode estar inacessível.`);return{errors,warnings};}
function renderValidation(result){const total=result.errors.length+result.warnings.length;validationSummary.textContent=total===0?'Mapa validado: nenhum problema encontrado.':`Validação concluída: ${result.errors.length} erro(s), ${result.warnings.length} aviso(s).`;const lines=[];if(result.errors.length){lines.push('Erros:');result.errors.forEach(m=>lines.push(`• ${m}`));}if(result.warnings.length){if(lines.length)lines.push('');lines.push('Avisos:');result.warnings.forEach(m=>lines.push(`• ${m}`));}validationList.textContent=lines.join('\n');}
function runValidation(showStatus=true){const result=validateMap();renderValidation(result);if(showStatus)setStatus(result.errors.length?'Validação: há erros no mapa.':result.warnings.length?'Validação concluída com avisos.':'Mapa validado com sucesso.');return result;}runValidationBtn&&(runValidationBtn.onclick=()=>runValidation(true));validateBtn&&(validateBtn.onclick=()=>runValidation(true));


/* src/editor/templates.js */
'use strict';
function builtInTemplates(){const a=freshMap();a.meta.name='Arena básica';a.grid={cols:20,rows:12};a.spawn={c:1,r:5};a.goal={c:18,r:5};a.coins=[{id:1,c:10,r:5}];const c=freshMap();c.meta.name='Corredor com checkpoint';c.grid={cols:28,rows:10};c.spawn={c:1,r:4};c.goal={c:26,r:4};c.checkpoints=[{id:1,c:12,r:4}];c.walls=[{id:1,c:0,r:2,w:28,h:1},{id:2,c:0,r:7,w:28,h:1}];c.enemies=[{id:1,type:'moving',mode:'patrol',speed:90,start:{x:9*CELL,y:4.5*CELL},end:{x:18*CELL,y:4.5*CELL},angle:0}];const l=freshMap();l.meta.name='Labirinto curto';l.grid={cols:24,rows:14};l.spawn={c:1,r:1};l.goal={c:22,r:12};l.walls=[{id:1,c:3,r:0,w:1,h:10},{id:2,c:6,r:4,w:1,h:10},{id:3,c:9,r:0,w:1,h:10},{id:4,c:12,r:4,w:1,h:10},{id:5,c:15,r:0,w:1,h:10},{id:6,c:18,r:4,w:1,h:10}];return[{key:'builtin:arena',name:'Arena básica',map:a},{key:'builtin:corridor',name:'Corredor com checkpoint',map:c},{key:'builtin:maze',name:'Labirinto curto',map:l}];}
function customTemplates(){try{const raw=parseJsonWithLimit(localStorage.getItem('sanMapEditorV11Templates')||localStorage.getItem('sanMapEditorV7Templates')||'[]');if(!Array.isArray(raw))return[];const safe=[];for(const item of raw.slice(0,SECURITY.MAX_TEMPLATES)){if(!isRecord(item)||!isRecord(item.map))continue;try{assertMapInputLimits(item.map);}catch{continue;}const key=cleanText(item.key,100,''),name=cleanText(item.name,SECURITY.MAX_TEMPLATE_NAME,'Template');if(key)safe.push({key,name,map:item.map});}return safe;}catch{return[];}}
function saveCustomTemplates(list){try{localStorage.setItem('sanMapEditorV11Templates',JSON.stringify(Array.isArray(list)?list.slice(0,SECURITY.MAX_TEMPLATES):[]));return true;}catch{setStatus('Não foi possível salvar o template no armazenamento local.');return false;}}
function refreshTemplates(){templatesCache=[...builtInTemplates(),...customTemplates()];if(!templateSelect)return;templateSelect.replaceChildren();for(const item of templatesCache){const o=document.createElement('option');o.value=String(item.key);o.textContent=cleanText(item.name,SECURITY.MAX_TEMPLATE_NAME,'Template');templateSelect.appendChild(o);}}
function loadTemplateByKey(key){const item=templatesCache.find(t=>t.key===key);if(!item)return;try{normalizeMap(cloneJson(item.map));resizeCanvas();fitMapToGrid();syncDocumentControls();clearPending();clearSelection();resetHistory();setMode('edit');draw();runValidation(false);setStatus(`Template carregado: ${cleanText(item.name,SECURITY.MAX_TEMPLATE_NAME,'Template')}`);}catch(e){setStatus('Template recusado: '+(e?.message||'dados inválidos.'));}}
refreshTemplates();loadTemplateBtn&&(loadTemplateBtn.onclick=()=>{if(templateSelect.value)loadTemplateByKey(templateSelect.value);});saveTemplateBtn&&(saveTemplateBtn.onclick=()=>{if(customTemplates().length>=SECURITY.MAX_TEMPLATES){setStatus(`Limite de ${SECURITY.MAX_TEMPLATES} templates próprios atingido.`);return;}const typed=prompt('Nome do template:',map.meta?.name||'Meu template');if(typed===null)return;const name=cleanText(typed,SECURITY.MAX_TEMPLATE_NAME,'');if(!name){setStatus('O template precisa de um nome.');return;}try{assertMapInputLimits(map);}catch(e){setStatus('Template não salvo: '+e.message);return;}const list=customTemplates(),key='custom:'+Date.now();list.push({key,name,map:cloneJson(map)});if(saveCustomTemplates(list)){refreshTemplates();templateSelect.value=key;setStatus('Template salvo localmente.');}});deleteTemplateBtn&&(deleteTemplateBtn.onclick=()=>{const key=templateSelect.value;if(!key||!key.startsWith('custom:')){setStatus('Selecione um template próprio para excluir.');return;}saveCustomTemplates(customTemplates().filter(t=>t.key!==key));refreshTemplates();setStatus('Template excluído.');});


/* src/ui/actions.js */
'use strict';
$('editBtn').onclick=()=>setMode('edit');$('testBtn').onclick=()=>setMode('test');$('resetBtn').onclick=()=>{if(mode==='test')startTest();else{clearPending();clearSelection();draw();setStatus('Edição limpa de seleções temporárias.');}};$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;
$('newBtn').onclick=()=>{if(confirm('Criar um mapa novo? Alterações não exportadas continuarão apenas no histórico desta sessão.')){map=freshMap();resizeCanvas();deaths=0;clearPending();clearSelection();syncDocumentControls();resetHistory();setMode('edit');draw();setStatus('Novo mapa criado.');}};
$('openBtn').onclick=()=>fileInput.click();fileInput.onchange=()=>{const f=fileInput.files?.[0];if(!f)return;if(f.size>SECURITY.MAX_IMPORT_BYTES){setStatus(`Arquivo recusado: limite de ${Math.round(SECURITY.MAX_IMPORT_BYTES/1000000*10)/10} MB.`);fileInput.value='';return;}const r=new FileReader();r.onload=()=>{try{normalizeMap(parseMapJson(String(r.result)));clearPending();clearSelection();syncDocumentControls();resetHistory();setMode('edit');draw();setStatus('Mapa carregado: '+cleanText(f.name,120,'arquivo.json'));}catch(e){setStatus('Mapa recusado: '+(e?.message||'JSON inválido.'));}fileInput.value='';};r.onerror=()=>{setStatus('Não foi possível ler o arquivo.');fileInput.value='';};r.readAsText(f,'utf-8');};
$('downloadBtn').onclick=()=>{try{assertMapInputLimits(map);}catch(e){setStatus('Não foi possível salvar: '+e.message);return;}syncLevelNameFromInput({finalize:true});const json=JSON.stringify(map,null,2);jsonArea.value=json;if(!confirm('Deseja baixar esta fase em JSON?'))return;const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');const safe=(map.meta.name||'mapa_san').replace(/[^\w\-áéíóúãõç ]/gi,'').trim().replace(/\s+/g,'_').slice(0,80)||'mapa_san';a.href=url;a.download=safe+'.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setStatus('JSON salvo.');};
$('generateBtn').onclick=()=>{try{assertMapInputLimits(map);}catch(e){setStatus('JSON não gerado: '+e.message);return;}syncLevelNameFromInput({finalize:true});jsonArea.value=JSON.stringify(map,null,2);setStatus('Caixa JSON atualizada.');};$('loadTextBtn').onclick=()=>{try{normalizeMap(parseMapJson(jsonArea.value));clearPending();clearSelection();syncDocumentControls();resetHistory();setMode('edit');draw();setStatus('JSON carregado da caixa.');}catch(e){setStatus('JSON recusado: '+(e?.message||'conteúdo inválido.'));}};
addEventListener('keydown',ev=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo();return;}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='y'){ev.preventDefault();redo();return;}if(ev.key==='Delete'&&!typing&&mode==='edit'&&selected){deleteSelected();return;}if(mode!=='test'||typing)return;const k=ev.key.toLowerCase();keys[k]=true;if(k.startsWith('arrow'))ev.preventDefault();});addEventListener('keyup',ev=>keys[ev.key.toLowerCase()]=false);
const oldDownload=$('downloadBtn').onclick;$('downloadBtn').onclick=()=>{runValidation(false);oldDownload();};const oldTest=$('testBtn').onclick;$('testBtn').onclick=()=>{try{assertMapInputLimits(map);}catch(e){setStatus('Teste bloqueado: '+e.message);runValidation(false);return;}runValidation(false);oldTest();};
addEventListener('keydown',ev=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(typing)return;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='c'){ev.preventDefault();copySelectionToClipboard();}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='v'){ev.preventDefault();pasteClipboard(1);}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='d'){ev.preventDefault();duplicateSelection();}});


/* src/core/storage.js */
'use strict';function restoreDraft(){try{const s=localStorage.getItem('sanMapEditorV11Draft')||localStorage.getItem('sanMapEditorV7Draft')||localStorage.getItem('sanMapEditorV6Draft')||localStorage.getItem('sanMapEditorV5Draft');if(s){normalizeMap(parseMapJson(s));return true;}}catch{try{localStorage.removeItem('sanMapEditorV11Draft');}catch{}}return false;}


/* src/app.js */
'use strict';
restoreDraft();
normalizeMap(map);
syncDocumentControls();
resetHistory();
updateGuideButtons();
updateStatus();
refreshTemplates();
applyZoom();
draw();
document.querySelectorAll('.tool').forEach(btn=>btn.classList.toggle('active',btn.dataset.tool===tool));
