'use strict';
const SECURITY = Object.freeze({
  MAX_IMPORT_BYTES:2500000,MAX_JSON_CHARS:2500000,MAX_LEVEL_NAME:80,MAX_TEMPLATE_NAME:80,MAX_TEMPLATES:100,
  MAX_WALLS:4000,MAX_ENEMIES:500,MAX_PORTALS:1000,MAX_CHECKPOINTS:2000,MAX_KEY_DOORS:1000,MAX_BUTTONS:2000,MAX_COINS:8000,
  MAX_ROUTE_POINTS_PER_ENEMY:512,MAX_TOTAL_ROUTE_POINTS:10000,MAX_TOTAL_OBJECTS:12000,MAX_ID:2147483647
});
function isRecord(v){return !!v&&typeof v==='object'&&!Array.isArray(v);}
function cleanText(v,max=80,f=''){const s=String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);return s||f;}
function finiteNumber(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function finiteInteger(v,f=0){return Math.trunc(finiteNumber(v,f));}
function safeBoolean(v,f=false){return typeof v==='boolean'?v:f;}
function parseJsonWithLimit(text,max=SECURITY.MAX_JSON_CHARS){const s=String(text??'');if(s.length>max)throw new Error(`JSON excede o limite de ${Math.round(max/1000000*10)/10} MB.`);return JSON.parse(s);}
function mapInputStats(data){const s={walls:Array.isArray(data?.walls)?data.walls.length:0,enemies:Array.isArray(data?.enemies)?data.enemies.length:0,portals:Array.isArray(data?.portals)?data.portals.length:0,checkpoints:Array.isArray(data?.checkpoints)?data.checkpoints.length:0,keyDoors:Array.isArray(data?.keyDoors)?data.keyDoors.length:0,buttons:Array.isArray(data?.buttons)?data.buttons.length:0,coins:Array.isArray(data?.coins)?data.coins.length:0,routePoints:0};if(Array.isArray(data?.enemies))for(const e of data.enemies)if(Array.isArray(e?.route))s.routePoints+=e.route.length;s.totalObjects=s.walls+s.enemies+s.portals+s.checkpoints+s.keyDoors+s.buttons+s.coins+2;return s;}
function assertMapInputLimits(data){if(!isRecord(data))throw new Error('O JSON precisa conter um objeto de mapa na raiz.');const ls=[['walls',SECURITY.MAX_WALLS,'paredes'],['enemies',SECURITY.MAX_ENEMIES,'inimigos'],['portals',SECURITY.MAX_PORTALS,'portais'],['checkpoints',SECURITY.MAX_CHECKPOINTS,'checkpoints'],['keyDoors',SECURITY.MAX_KEY_DOORS,'chaves/portas'],['buttons',SECURITY.MAX_BUTTONS,'botões'],['coins',SECURITY.MAX_COINS,'moedas']];for(const [k,m,l] of ls){const v=data[k];if(v!==undefined&&!Array.isArray(v))throw new Error(`Campo “${k}” inválido: era esperado um array.`);if(Array.isArray(v)&&v.length>m)throw new Error(`Mapa recusado: máximo de ${m} ${l}.`);}let rp=0;if(Array.isArray(data.enemies))for(const e of data.enemies){if(!isRecord(e))continue;if(e.route!==undefined&&!Array.isArray(e.route))throw new Error('Rota de inimigo inválida.');if(Array.isArray(e.route)){if(e.route.length>SECURITY.MAX_ROUTE_POINTS_PER_ENEMY)throw new Error(`Mapa recusado: uma rota possui mais de ${SECURITY.MAX_ROUTE_POINTS_PER_ENEMY} pontos.`);rp+=e.route.length;}}if(rp>SECURITY.MAX_TOTAL_ROUTE_POINTS)throw new Error(`Mapa recusado: máximo de ${SECURITY.MAX_TOTAL_ROUTE_POINTS} pontos de rota no total.`);const s=mapInputStats(data);if(s.totalObjects>SECURITY.MAX_TOTAL_OBJECTS)throw new Error(`Mapa recusado: máximo de ${SECURITY.MAX_TOTAL_OBJECTS} objetos.`);return s;}
function parseMapJson(text){const d=parseJsonWithLimit(text);assertMapInputLimits(d);return d;}
function cloneJson(v){return JSON.parse(JSON.stringify(v));}
function collectionLimit(k){return ({walls:SECURITY.MAX_WALLS,enemies:SECURITY.MAX_ENEMIES,portals:SECURITY.MAX_PORTALS,checkpoints:SECURITY.MAX_CHECKPOINTS,keyDoors:SECURITY.MAX_KEY_DOORS,buttons:SECURITY.MAX_BUTTONS,coins:SECURITY.MAX_COINS})[k]||SECURITY.MAX_TOTAL_OBJECTS;}
function canAddToCollection(k,a=1){const l=map?.[k],m=collectionLimit(k);if(!Array.isArray(l))return false;if(l.length+a<=m)return true;setStatus(`Limite de segurança atingido: ${m} item(ns) em ${k}.`);return false;}
